### ISSUE TITLE
执行sh scripts/0_pretrain.sh报错，ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by chen10089** [yuqianghan/editretro#10]
![Uploading 1725595343340.jpg…]()

**Comment by chen10089** [comment]
sh scripts/0_pretrain.sh 
run_n:20240906_114308, max_tokens:12000, databin=./datasets/USPTO_50K/aug20/data-bin, noise_type=random_delete, architecture=pretrain_mlm_editretro, arguments=--fp16, , 0
Traceback (most recent call last):
  File "/baode_bioinformatics/home/chenancheng/miniconda3/envs/retro/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/baode_bioinformatics/home/chenancheng/code/retro/editretro-master/fairseq/fairseq_cli/train.py", line 322, in cli_main
    main(args)
  File "/baode_bioinformatics/home/chenancheng/code/retro/editretro-master/fairseq/fairseq_cli/train.py", line 82, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/baode_bioinformatics/home/chenancheng/code/retro/editretro-master/fairseq/fairseq/checkpoint_utils.py", line 157, in load_checkpoint
    trainer.lr_step(epoch_itr.epoch)
  File "/baode_bioinformatics/home/chenancheng/code/retro/editretro-master/fairseq/fairseq/trainer.py", line 480, in lr_step
    self.lr_scheduler.step(epoch, val_loss)
  File "/baode_bioinformatics/home/chenancheng/code/retro/editretro-master/fairseq/fairseq/trainer.py", line 103, in lr_scheduler
    self._build_optimizer()  # this will initialize self._lr_scheduler
  File "/baode_bioinformatics/home/chenancheng/code/retro/editretro-master/fairseq/fairseq/trainer.py", line 122, in _build_optimizer
    self._optimizer = optim.FP16Optimizer.build_optimizer(
  File "/baode_bioinformatics/home/chenancheng/code/retro/editretro-master/fairseq/fairseq/optim/fp16_optimizer.py", line 257, in build_optimizer
    return cls(args, params, fp32_optimizer, fp32_params)
  File "/baode_bioinformatics/home/chenancheng/code/retro/editretro-master/fairseq/fairseq/optim/fp16_optimizer.py", line 227, in __init__
    scale_window = int(2**14 / args.distributed_world_size / args.update_freq[0])
ZeroDivisionError: division by zero
