### ISSUE TITLE
不Finetune怎么运行generate

### ISSUE THREAD

**Issue by chen10089** [yuqianghan/editretro#15]
(editretro) [mahaohui@gpu004 editretro]$ sh scripts/2_generate_50k.sh 
Namespace(inputs=['/sugon_data/mahaohui/chenancheng/code/editretro/results/pretrain/20241030_135709/checkpoints'], output='/sugon_data/mahaohui/chenancheng/code/editretro/results/pretrain/20241030_135709/generations/1/checkpoint.pt', num_epoch_checkpoints=40, num_update_checkpoints=None, checkpoint_upper_bound=40)
Traceback (most recent call last):
  File "/sugon_data/mahaohui/chenancheng/code/editretro/./utils/average_checkpoints.py", line 140, in <module>
    main()
  File "/sugon_data/mahaohui/chenancheng/code/editretro/./utils/average_checkpoints.py", line 129, in main
    args.inputs = last_n_checkpoints(
  File "/sugon_data/mahaohui/chenancheng/code/editretro/./utils/average_checkpoints.py", line 87, in last_n_checkpoints
    raise Exception('Found {} checkpoint files but need at least {}', len(entries), n)
Exception: ('Found {} checkpoint files but need at least {}', 0, 40)
Traceback (most recent call last):
  File "/sugon_data/mahaohui/miniconda3/envs/editretro/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/sugon_data/mahaohui/chenancheng/code/editretro/fairseq/fairseq_cli/generate.py", line 207, in cli_main
    main(args)
  File "/sugon_data/mahaohui/chenancheng/code/editretro/fairseq/fairseq_cli/generate.py", line 45, in main
    models, _model_args = checkpoint_utils.load_model_ensemble(
  File "/sugon_data/mahaohui/chenancheng/code/editretro/fairseq/fairseq/checkpoint_utils.py", line 186, in load_model_ensemble
    ensemble, args, _task = load_model_ensemble_and_task(
  File "/sugon_data/mahaohui/chenancheng/code/editretro/fairseq/fairseq/checkpoint_utils.py", line 198, in load_model_ensemble_and_task
    raise IOError("Model file not found: {}".format(filename))
OSError: Model file not found: /sugon_data/mahaohui/chenancheng/code/editretro/results/pretrain/20241030_135709/generations/1/checkpoint.pt
0 0 0
Reading predictions from file ...
Canonicalizing predictions using Process Number  104
Prediction data size  0
Reading targets from file ...
Origin File Length 0
0it [00:00, ?it/s]
Origin Target Length,  0
Cutted Length,  0
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/sugon_data/mahaohui/chenancheng/code/editretro/./utils/score.py", line 403, in <module>
    main(opt)
  File "/sugon_data/mahaohui/chenancheng/code/editretro/./utils/score.py", line 263, in main
    i + 1, accuracy[i] / data_size * 100,
ZeroDivisionError: division by zero

**Comment by yuqianghan** [comment]
你好，由于在预训练的时候在 encoder 上有使用 Masked LM, 所以词表里多了一个  token， 模型里多了一个 MLM head。

1. 取消注释 1_finetune_50k.sh 中 27-39 行代码；
2. 注释掉 41 行以后的代码；
3. 使用处理后的 checkpoint 作为 2_generate_50k.sh 的模型。
