### ISSUE TITLE
如果在finetune_50k.pt的基础上继续finetune, 1_finetune.sh需要改什么吗？

### ISSUE THREAD

**Issue by mspythontu** [yuqianghan/editretro#17]
#!/bin/bash
gpus=0 #
noise_type=random_delete_shuffle #
model_args="--fp16" #
architecture=editretro_nat #
task=translation_retro #
loss=nat_loss #
update=1 #
lr=0.0001 #
max_tokens=8192 #
max_epoch=1500 #
max_update=300000 #
exp_n=finetune #
run_n=$(date "+%Y%m%d_%H%M%S") #
root_dir=results #
exp_dir=$root_dir/$exp_n #
mkdir -p $exp_dir #
model_dir=${exp_dir}/$run_n/checkpoints #
mkdir -p $model_dir #
databin=/home/top/projects/editretro/datasets/USPTO_50K/aug20/data-bin # ./datasets/USPTO_50K/aug20/data-bin # databin processed by fairseq
pretrain_ckpt_path=/home/top/projects/editretro/results/pretrain/20240827_170548/checkpoints  # results/pretrain/xxxxxx/checkpoints  # pretrain checkpoint path
pretrain_ckpt_name=${pretrain_ckpt_path}/checkpoint_pretrain.pt  # the name used to represent the pretrained ckpt
python utils/average_checkpoints.py --inputs $pretrain_ckpt_path --output ${pretrain_ckpt_name} --num-update-checkpoints 5 # --num-epoch-checkpoints 10 \
python utils/pretrain_ckpt_utils.py --inputckpt ${pretrain_ckpt_name} --outputckpt ${pretrain_ckpt_name} #
gpu_ids=$(echo $gpus | sed "s/,/ /g") #
gpu_n=$(echo $gpu_ids | wc -w) #
CUDA_VISIBLE_DEVICES=$gpus CUDA_LAUNCH_BLOCKING=1 fairseq-train --user-dir editretro $databin --save-dir $model_dir --ddp-backend=no_c10d --task  $task --criterion $loss  --arch $architecture  --noise $noise_type  --optimizer adam --adam-betas '(0.9,0.98)' --lr $lr --lr-scheduler inverse_sqrt --min-lr '1e-09' --warmup-updates 10000 --warmup-init-lr '1e-07' --label-smoothing 0.1 --share-all-embeddings --dropout 0.3 --weight-decay 0.001 --decoder-learned-pos --encoder-learned-pos --max-tokens-valid 4000 --log-format 'simple' --log-interval 100 --fixed-validation-seed 7 --max-tokens 8000 --save-interval-updates 10000 --keep-last-epochs 20 --max-epoch ${max_epoch} --max-update ${max_update} --alpha-ratio 0.2 --dae-ratio 0.2 --fp16  --restore-file ${pretrain_ckpt_name} --reset-optimizer --reset-lr-scheduler --reset-meters --reset-dataloader --distributed-world-size $gpu_n > ${model_dir}/finetune.log #

以上，是否注释掉python utils/average_checkpoints.py --inputs $pretrain_ckpt_path --output ${pretrain_ckpt_name} --num-update-checkpoints 5 # --num-epoch-checkpoints 10 \和
python utils/pretrain_ckpt_utils.py --inputckpt ${pretrain_ckpt_name} --outputckpt ${pretrain_ckpt_name} #，并且把pretrain_ckpt_name的路径改成finetune_50k.pt的路径即可，python utils/pretrain_ckpt_utils.py --inputckpt ${pretrain_ckpt_name} --outputckpt ${pretrain_ckpt_name}的意义是什么呢

**Comment by yuqianghan** [comment]
1.   pretrain_ckpt_utils.py 的作用是删除预训练使用的 mask token 以及 encoder 部分的 masked_lm_head.
2.  如果想要继续训练，请参考最新的 `1_finetune_50k.sh`, 注释掉 
`python utils/average_checkpoints.py --inputs ${pretrain_ckpt_path} \`
以及
`python utils/pretrain_ckpt_utils.py \`
并把 `ckpt_name` 指向 `finetune_50k.pt`
如果是想要继续训练，还需要注释掉
`--reset-optimizer --reset-lr-scheduler --reset-meters --reset-dataloader \`
如果是想要用 `finetune_50k.pt` 作为初始化，则不需要注释上面一行。

**Comment by mspythontu** [comment]
谢谢解释，明白了

**Comment by mspythontu** [comment]
Traceback (most recent call last):
  File "/home/top/anaconda3/envs/editretro/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/top/projects/editretro/fairseq/fairseq_cli/train.py", line 322, in cli_main
    main(args)
  File "/home/top/projects/editretro/fairseq/fairseq_cli/train.py", line 93, in main
    train(args, trainer, task, epoch_itr)
  File "/home/top/anaconda3/envs/editretro/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/top/projects/editretro/fairseq/fairseq_cli/train.py", line 173, in train
    log_output = trainer.train_step(samples)
  File "/home/top/anaconda3/envs/editretro/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/top/projects/editretro/fairseq/fairseq/trainer.py", line 362, in train_step
    self.args.distributed_world_size / sample_size)
ZeroDivisionError: float division by zero

sh ./scripts/1_finetune_full.sh 时出现这个错误，是怎么回事呢

**Comment by yuqianghan** [comment]
OOM 的情况需要减小 max_tokens  参数，
1. 修改 max_tokens (8192 的倍数)，同时需要修改学习率 lr；
2. 修改 max_tokens (8192 的倍数)，同时修改 update，实现梯度累积，例如 max_tokens=20480，update=2；

推荐方式2.

**Comment by mspythontu** [comment]
finetune的时候out of cuda memory也是修改这两个参数吗？

**Comment by yuqianghan** [comment]
是的

**Comment by mspythontu** [comment]
谢谢解释

**Comment by mspythontu** [comment]
您好，当我注释掉--reset-optimizer --reset-lr-scheduler --reset-meters --reset-dataloader，模型就不训练了，请指教！

**Comment by yuqianghan** [comment]
你好，在 pre-train 和 fine-tune 流程中，fine-tune 的时候常用做法是设置

`
--reset-optimizer --reset-lr-scheduler --reset-meters --reset-dataloader 
`

这样会重新设置数据加载和模型参数更新，因为 pretrain 和 finetune 过程的训练任务和数据均不相同，pretrained 的参数是为 finetune 过程提供比较好的初始化。

"模型就不训练了" 的原因是在预训练的过程中，lr 已经趋于不变，而且已经降低到非常小的值。

**Comment by mspythontu** [comment]
我只把--reset-lr-scheduler注释掉，也就是lr和之前的预训练不变，却能继续训练；当再把--reset-optimizer注释掉后就不能继续训练了。请教一下是否和“预训练的过程中，lr 已经趋于不变，而且已经降低到非常小的值”矛盾？注释掉--reset-lr-scheduler是否是表示lr与之前的lr不变？谢谢！

**Comment by yuqianghan** [comment]
1. lr_scheduler 的作用是按照一定的方式在训练过程中不断减小 lr, --reset-lr-scheduler 以及 --reset-optimizer 的作用建议你查阅 fairseq 文档 https://fairseq.readthedocs.io/en/latest/command_line_tools.html
2. 你是在 pretrained 的基础上继续 finetune 还是在 finetune_50k.pt 的基础上继续 finetue?

**Comment by mspythontu** [comment]
1、看了文档，应该是 --reset-optimizer 的作用之一是重置lr。
2、我是在finetune_50k.pt 的基础上继续 finetue，如果注释掉--reset-optimizer --reset-lr-scheduler --reset-meters --reset-dataloader，模型就不训练了，说明lr已经降低到非常低的数值，有什么更好的方法在finetune后继续finetune吗？谢谢！

**Comment by yuqianghan** [comment]
请问你是用 uspto-50k 数据集在 finetune_50k.pt 上继续 finetune? 还是换了其它新数据集？

**Comment by mspythontu** [comment]
您好！我换用了自己的数据集，数据量可能有8百万条。

**Comment by yuqianghan** [comment]
1. 这种情况下应该是要基于 pretrain 的 checkpoint 在你的数据集上直接进行 finetune, 可以下载我们提供的 pretrained checkpoint, 然后在 finetune 里换成你自己的数据集。
2. 你用这么大的数据量在 finetune_50k.pt 上进行微调，即使是设置了以上的 --reset 命令可以继续微调，也不是正常的操作。

**Comment by mspythontu** [comment]
好的，您好！我看了pretrain的readme，pretrain的模型是训练了upsto_full的。如果数据只有100W条左右，有什么建议吗？谢谢！

**Comment by yuqianghan** [comment]
你好，uspto_full 原始数据里反应的数量也只有约80W，进行 augmentation 以后数量会多一些。如果你的原始反应数量有 100W 左右的话，数据集还是比较大的，可以直接基于我们提供的 pretrained checkpoint 进行微调。
或者你也可以尝试进行数据增强，无需预训练，直接从头训练模型。

**Comment by mspythontu** [comment]
好的，谢谢指导
