### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by chen10089** [yuqianghan/editretro#18]
bash ./scripts/0_pretrain.sh
run_n:20241128_133509, max_tokens:49152, databin=datasets/USPTO_Pretrain/pretrain/data-bin, noise_type=random_mask, architecture=pretrain_mlm_editretro, 0, 1
Traceback (most recent call last):
  File "/sugon_data/mahaohui/miniconda3/envs/editretro/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/sugon_data/mahaohui/miniconda3/envs/editretro/lib/python3.10/site-packages/fairseq-0.9.0-py3.10-linux-x86_64.egg/fairseq_cli/train.py", line 322, in cli_main
    main(args)
  File "/sugon_data/mahaohui/miniconda3/envs/editretro/lib/python3.10/site-packages/fairseq-0.9.0-py3.10-linux-x86_64.egg/fairseq_cli/train.py", line 93, in main
    train(args, trainer, task, epoch_itr)
  File "/sugon_data/mahaohui/miniconda3/envs/editretro/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/sugon_data/mahaohui/miniconda3/envs/editretro/lib/python3.10/site-packages/fairseq-0.9.0-py3.10-linux-x86_64.egg/fairseq_cli/train.py", line 173, in train
    log_output = trainer.train_step(samples)
  File "/sugon_data/mahaohui/miniconda3/envs/editretro/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/sugon_data/mahaohui/miniconda3/envs/editretro/lib/python3.10/site-packages/fairseq-0.9.0-py3.10-linux-x86_64.egg/fairseq/trainer.py", line 362, in train_step
    self.args.distributed_world_size / sample_size)
ZeroDivisionError: float division by zero

这里我按照文档一步步做的，执行0_pretrain.sh这里报错

**Comment by yuqianghan** [comment]
根据 error log 没法确定具体的错误原因，有可能是因为分布式 distributed_world_size 设置的原因。你是用的几张卡？

**Comment by chen10089** [comment]
> 根据 error log 没法确定具体的错误原因，有可能是因为分布式 distributed_world_size 设置的原因。你是用的几张卡？

可能是这个原因，我用的是8卡的机器，然后我用一张卡跑的，我把gpu_ids=1，gpu_n=1，可以跑了
